name = "DiffEqFlux"
uuid = "aae7a2af-3d4f-5e19-a356-7da93b79d9d0"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "0.6.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqSensitivity = "41bf760c-e81c-5289-8e54-58b1f1f8abe2"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
DiffEqBase = ">= 5.6"
julia = "1"
